"""Generate a drop-in determinism hardening patch.

The patch is deliberately conservative: it pins what can be pinned
without changing model semantics, and comments out what would (TF32,
deterministic-algorithms mode) so the user opts in knowingly.
"""

from __future__ import annotations

import os
from typing import Iterable, Optional

from .audit import Finding

PATCH_TEMPLATE = '''"""Determinism hardening, generated by seedtrace.

Import this module (or copy these lines) at the very top of your
entry-point script, BEFORE importing torch/numpy or any code that
consumes randomness. Environment variables here only take effect if
set before interpreter start; run via:

    seedtrace run --hashseed 0 -- python your_script.py

or export PYTHONHASHSEED=0 in your launcher/CI config.
"""

import os

# --- environment (set before heavy imports; see docstring above) ---
os.environ.setdefault("PYTHONHASHSEED", "0")
os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
# Uncomment to pin BLAS threading (thread count changes summation order):
# os.environ.setdefault("OMP_NUM_THREADS", "1")
# os.environ.setdefault("MKL_NUM_THREADS", "1")

# --- global RNG seeding ------------------------------------------------
SEED = int(os.environ.get("SEEDTRACE_SEED", "42"))

import random as _random

_random.seed(SEED)

try:
    import numpy as _np

    _np.random.seed(SEED % (2**32))
except ImportError:
    _np = None

try:
    import torch as _torch

    _torch.manual_seed(SEED)
    if _torch.cuda.is_available():
        _torch.cuda.manual_seed_all(SEED)

    # --- PyTorch determinism knobs ---------------------------------
    # Algorithm selection by runtime timing breaks reproducibility:
    _torch.backends.cudnn.benchmark = False

    # TF32 silently reduces matmul/conv precision. Enable/disable to
    # match how your reference results were produced:
    # _torch.backends.cuda.matmul.allow_tf32 = False
    # _torch.backends.cudnn.allow_tf32 = False

    # Strict mode: torch raises instead of silently using a
    # nondeterministic kernel. Cost: some ops lose GPU support.
    # _torch.use_deterministic_algorithms(True, warn_only=True)

    # DataLoader workers do NOT inherit the seeds above. Use:
    #
    # def _seed_worker(worker_id):
    #     import numpy as np, random
    #     base = _torch.initial_seed() % (2**32)
    #     np.random.seed(base + worker_id)
    #     random.seed(base + worker_id)
    # DataLoader(..., worker_init_fn=_seed_worker,
    #            generator=torch.Generator().manual_seed(SEED))
except ImportError:
    _torch = None
'''


def render_patch(extra_findings: Optional[Iterable[Finding]] = None) -> str:
    text = PATCH_TEMPLATE
    hints = []
    for f in extra_findings or ():
        loc = f.file or "(environment)"
        if f.line:
            loc = f"{loc}:{f.line}"
        hints.append(f"#   - [{f.severity}] {f.id} at {loc}: {f.fix}")
    if hints:
        text += "\n\n# --- hazards seedtrace audit found in your code ---\n" + "\n".join(hints)
    return text


def write_patch(path: str = "determinism_patch.py") -> str:
    full = os.path.abspath(path)
    with open(full, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_patch())
    return full
